[workspace]
authors = ["dvl0p <245560527+dvl0p@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "zapp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "go build -o ./bin/ ./cmd/zapp"
exec = { cmd = "./bin/zapp", depends-on = ["build"] }

[dependencies]
go = ">=1.26.2,<2"
